In [10]:
import pandas as pd
import numpy as np

In [11]:
import kagglehub
path = kagglehub.dataset_download("martj42/international-football-results-from-1872-to-2017")

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.13), please consider upgrading to the latest version (1.0.0).

In [12]:
#to see what files I got
from pathlib import Path
root = Path(r"C:\Users\X\.cache\kagglehub\datasets\martj42\international-football-results-from-1872-to-2017\versions\110")
for p in sorted(root.iterdir()):
    print(p.name)

former_names.csv
goalscorers.csv
results.csv
shootouts.csv

In [18]:
df = pd.read_csv(root / "results.csv")
print(df.shape)
print(df.head())
df.info()

(49287, 9)
         date home_team away_team  home_score  away_score tournament     city  \
0  1872-11-30  Scotland   England         0.0         0.0   Friendly  Glasgow
1  1873-03-08   England  Scotland         4.0         2.0   Friendly   London
2  1874-03-07  Scotland   England         2.0         1.0   Friendly  Glasgow
3  1875-03-06   England  Scotland         2.0         2.0   Friendly   London
4  1876-03-04  Scotland   England         3.0         0.0   Friendly  Glasgow

    country  neutral
0  Scotland    False
1   England    False
2  Scotland    False
3   England    False
4  Scotland    False
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49287 entries, 0 to 49286
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        49287 non-null  object
 1   home_team   49287 non-null  object
 2   away_team   49287 non-null  object
 3   home_score  49215 non-null  float64
 4   away_score  49215 non-null  float64
 5   tournament  49287 non-null  object
 6   city        49287 non-null  object
 7   country     49287 non-null  object
 8   neutral     49287 non-null  bool
dtypes: bool(1), float64(2), object(6)
memory usage: 3.1+ MB

In [19]:
df.describe()

         home_score    away_score
count  49215.000000  49215.000000
mean       1.756091      1.182404
std        1.770617      1.401770
min        0.000000      0.000000
25%        1.000000      0.000000
50%        1.000000      1.000000
75%        2.000000      2.000000
max       31.000000     21.000000

In [20]:
df.isnull().sum()

date           0
home_team      0
away_team      0
home_score    72
away_score    72
tournament     0
city           0
country        0
neutral        0
dtype: int64

In [ ]:
df.duplicated().sum() #displayed as a NumPy type instead of a plain Python int
#to display it just as a number
int(df.duplicated().sum())

0

In [ ]:
df.duplicated() #scans each row and checks if it has appeared more than once; if yes -> True

0        False
1        False
2        False
3        False
4        False
         ...
49282    False
49283    False
49284    False
49285    False
49286    False
Length: 49287, dtype: bool

In [ ]:
df[df['away_score']>1.0] #will return the whole df

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
6,1877-03-03,England,Scotland,1.0,3.0,Friendly,London,England,False
7,1877-03-05,Wales,Scotland,0.0,2.0,Friendly,Wrexham,Wales,False
8,1878-03-02,Scotland,England,7.0,2.0,Friendly,Glasgow,Scotland,False
...,...,...,...,...,...,...,...,...,...
49194,2026-03-31,Peru,Honduras,2.0,2.0,Friendly,Madrid,Spain,True
49201,2026-03-31,South Africa,Panama,1.0,2.0,Friendly,Cape Town,South Africa,False
49204,2026-03-31,United States,Portugal,0.0,2.0,Friendly,Atlanta,United States,False
49209,2026-03-31,Sweden,Poland,3.0,2.0,FIFA World Cup qualification,Solna,Sweden,False
49211,2026-03-31,Czech Republic,Denmark,2.0,2.0,FIFA World Cup qualification,Prague,Czech Republic,False

In [ ]:
df['away_score']>1.0 #this will return indexes with True/False whether it satisfies the condition

0        False
1         True
2        False
3         True
4        False
         ...
49282    False
49283    False
49284    False
49285    False
49286    False
Name: away_score, Length: 49287, dtype: bool

In [14]:
df2 = pd.read_csv(root / "goalscorers.csv")
print(df2.shape)
print(df2.head())

(47601, 8)
         date  home_team away_team       team            scorer  minute  \
0  1916-07-02      Chile   Uruguay    Uruguay   José Piendibene    44.0
1  1916-07-02      Chile   Uruguay    Uruguay  Isabelino Gradín    55.0
2  1916-07-02      Chile   Uruguay    Uruguay  Isabelino Gradín    70.0
3  1916-07-02      Chile   Uruguay    Uruguay   José Piendibene    75.0
4  1916-07-06  Argentina     Chile  Argentina     Alberto Ohaco     2.0

   own_goal  penalty
0     False    False
1     False    False
2     False    False
3     False    False
4     False    False

In [15]:
df3 = pd.read_csv(root / "former_names.csv")
print(df3.shape)
print(df3.head())

(36, 4)
          current                former  start_date    end_date
0           Benin               Dahomey  1959-11-08  1975-11-30
1    Burkina Faso           Upper Volta  1960-04-14  1984-08-04
2         Curaçao  Netherlands Antilles  1957-03-03  2010-10-10
3  Czechoslovakia               Bohemia  1903-04-05  1919-01-01
4  Czechoslovakia   Bohemia and Moravia  1939-01-01  1945-05-01

In [16]:
df4 = pd.read_csv(root / "shootouts.csv")
print(df4.shape)
print(df4.head())

(675, 5)
         date    home_team         away_team       winner first_shooter
0  1967-08-22        India            Taiwan       Taiwan           NaN
1  1971-11-14  South Korea  Vietnam Republic  South Korea           NaN
2  1972-05-07  South Korea              Iraq         Iraq           NaN
3  1972-05-17     Thailand       South Korea  South Korea           NaN
4  1972-05-19     Thailand          Cambodia     Thailand           NaN

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49287 entries, 0 to 49286
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        49287 non-null  object
 1   home_team   49287 non-null  object
 2   away_team   49287 non-null  object
 3   home_score  49215 non-null  float64
 4   away_score  49215 non-null  float64
 5   tournament  49287 non-null  object
 6   city        49287 non-null  object
 7   country     49287 non-null  object
 8   neutral     49287 non-null  bool
dtypes: bool(1), float64(2), object(6)
memory usage: 3.1+ MB